bucketClaim:
  enabled: false
  name: bucket-name
  annotations:
    # This annotations makes it so ArgoCD will not complain if the CRD's are missing
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  # Name of the bucket in which to make the claim
  bucketName: tempo-bucket
  # Name of the storageClass that contains the bucket provider
  storageClassName: ceph-bucket

# https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml
tempo-distibuted:
  serviceMonitor:
    enabled: true
    labels:
      instance: primary
