apiVersion: v2
name: vault
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
dependencies:
  - name: vault
    version: "0.19.0"
    repository: "https://helm.releases.hashicorp.com"
    condition: vault.enabled
