cephObjectStores:
  - name: my-store
    namespace: rook-ceph
    annotations: {}
    spec:
      metadataPool:
        failureDomain: host
        replicated:
          size: 3
      dataPool:
        failureDomain: host
        erasureCoded:
          dataChunks: 2
          codingChunks: 1
      preservePoolsOnDelete: true
      gateway:
        sslCertificateRef:
        port: 80
        # securePort: 443
        instances: 1
      healthCheck:
        bucket:
          disabled: false
          interval: 60s

storageClass:
  - name: rook-ceph-bucket
    annotations: {}
    provisioner: rook-ceph.ceph.rook.io/bucket
    reclaimPolicy: Delete
    parameters:
      objectStoreName: my-store
      objectStoreNamespace: rook-ceph
      region: us-east-1
    allowVolumeExpansion: # true
    volumeBindingMode: # Immediate
    mountOptions:
    #   - debug
    allowedTopologies:
    #   - matchLabelExpressions:
    #     - key: failure-domain.beta.kubernetes.io/zone
    #       values:
    #       - us-central1-a
    #       - us-central1-b

objBucketClaims:
  - name: ceph-bucket
    annotations: {}
    spec:
      generateBucketName: ceph-bkt
      storageClassName: rook-ceph-bucket
