apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  labels:
    app: grafana-agent
spec:
  image: grafana/agent:v0.23.0
  logLevel: info
  serviceAccountName: grafana-agent

  configMaps:
    - agent-config

  containers:
    - name: grafana-agent
      args:
        - '-config.file=/var/lib/grafana-agent/configmaps/agent.yml'
        - '-config.expand-env=true'
        - '-reload-port=8081'
    - name: config-reloader
      args:
        - '--config-file=/var/lib/grafana-agent/configmaps/agent.yml'
        - '--config-envsubst-file=/var/lib/grafana-agent/config/agent.yml'
        - '--watch-interval=1m'
        - '--statefulset-ordinal-from-envvar=POD_NAME'
        - '--reload-url=http://127.0.0.1:8081/-/reload'

  metrics:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-metrics
    externalLabels:
      cluster: sccp

  logs:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-logs
