apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  labels:
    app: grafana-agent
spec:
  image: grafana/agent:v0.23.0
  logLevel: info
  serviceAccountName: grafana-agent
  metrics:
    global:
      remoteWrite:
      - url: {{ index .Values.metrics "remote-write-url" }}
    instanceSelector:
      matchLabels:
        agent: grafana-agent-metrics
    externalLabels:
      cluster: sccp

  logs:
    instanceSelector:
      matchLabels:
        agent: grafana-agent-logs

  integrations:
    agent:
      enabled: {{ .Values.integrations.agent.enabled }}
    node_exporter:
      enabled: {{ .Values.integrations.node_exporter.enabled }}
      rootfs_path: /host/root
      sysfs_path: /host/sys
      procfs_path: /host/proc
