apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  squid.conf: |
    pid_filename none
    logfile_rotate 0
    access_log stdio:/dev/stdout
    cache_log stdio:/dev/stdout
{{ (index .Values.config "squid.conf") | indent 4 }}
