apiVersion: v2
name: jaeger
description: An umbrella Helm chart for Jaeger
type: application
version: 0.1.3
dependencies:
  - name: jaeger
    version: 0.55.0
    repository: "https://jaegertracing.github.io/helm-charts"
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.11.2

