apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: grafana/tns-app:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        - http://db
        ports:
        - name: http-metrics
          containerPort: 80
        env:
        - name: JAEGER_AGENT_HOST
          value: {{ .Values.jaeger_agent_host }}
        - name: JAEGER_TAGS
          value: cluster=k8s,namespace={{ .Release.Namespace }}
        - name: JAEGER_SAMPLER_TYPE
          value: {{ .Values.jaeger_sampler_type }}
        - name: JAEGER_SAMPLER_PARAM
          value: {{ .Values.jaeger_sampler_param }}