apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - name: db
        image: grafana/tns-db:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        ports:
        - name: http-metrics
          containerPort: 80
        env:
        - name: JAEGER_AGENT_HOST
          value: {{ .Values.jaeger_agent_host }}
        - name: JAEGER_TAGS
          value: cluster=k8s,namespace={{ .Release.Namespace }}
        - name: JAEGER_SAMPLER_TYPE
          value: {{ .Values.jaeger_sampler_type }}
        - name: JAEGER_SAMPLER_PARAM
          value: {{ .Values.jaeger_sampler_param }}