{{- define "application" }}
  {{- $root := . }}
  {{- range $configPath, $_ := .Files.Glob "**/**/config.yaml" }}
    {{- $config := $root.Files.Get $configPath | fromYaml }}
    {{- range $config.apps }}
      {{- if get $root.Values.applications .name }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ template "helper.name" (dict "context" $root "name" .name ) }}
  # You'll usually want to add your resources to the argocd namespace.
  namespace: {{ $root.Release.Namespace }}
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Allows the creation of labels on apps
  labels:
    app: {{ template "helper.name" (dict "context" $root "name" .name ) }}
  {{- with $config.labels }}
{{ . | toYaml | indent 4 }}
  {{- end }}
  {{- with .labels }}
{{ . | toYaml | indent 4 }}
  {{- end }}
spec:
  # The project the application belongs to.
  project: {{ template "helper.name" (dict "context" $root "name" $config.name ) }}

  # Source of the application manifests
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision }}
{{- if .source.path }}
    path: {{ .source.path }}
{{- end }}
{{- if .source.chart }}
    chart: {{ .source.chart }}
{{- end }}
    helm:
      version: v3
      values: |
        {{- $valuesFilePath := printf "%s/%s/%s" ($configPath | dir) .name .source.valuesFile }}
        {{- $valuesFile := $root.Files.Get $valuesFilePath }}
{{ tpl $valuesFile $root | indent 8 }}
  # Destination cluster and namespace to deploy the application
  destination:
    server: {{ $root.Values.destinationServer | default $config.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ $config.namespace }}

  # Sync policy
  syncPolicy:
    syncOptions:
    {{- if .replace }}
      - Replace={{ .replace }}
    {{- end }}
    {{- if or $root.Values.destinationServer $config.destinationServer }}
      - CreateNamespace=true
    {{- else }}
      - CreateNamespace=false
    {{- end }}
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
