{{- define "networkPolicy" }}
  {{- $root := . }}
  {{- range $networkPolicyPath, $_ := .Files.Glob "**/**/network-policy.yaml" }}
    {{- $configPath := printf "%s/config.yaml" ($networkPolicyPath | dir) }}
    {{- $config := $root.Files.Get $configPath | fromYaml }}
    {{- $appEnabledInConfig := 0 }}
    {{- range $config.apps }}
      {{- if get $root.Values.applications .name }}
        {{- $appEnabledInConfig = 1 }}
      {{- end }}
    {{- end }}
    {{- if $appEnabledInConfig }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ $config.namespace }} 
spec:
{{- $networkPolicy := $root.Files.Get $networkPolicyPath }}
{{ tpl $networkPolicy $root | indent 2 }}        
    {{- end }}
  {{- end }}
{{- end }}
