---
{{- range .Values.applications }}
# {{ required ".Values.destination is required!" .Values.destination }}
# {{ required ".Values.overdriveConf.baseFolder is required!" .Values.overdriveConf.baseFolder }}
# {{ required ".Values.overdriveConf.envFolder is required!" .Values.overdriveConf.envFolder }}
# {{ required ".Values.overdriveConf.globalsFile is required!" .Values.overdriveConf.globalsFile }}
# {{ required "name is required for an application!" .name }}
# {{ required "project is required for an application!" .project }}
# {{ required "namespace is required for an application!" .namespace }}
# {{ required "chart.repo is required for an application!"  .chart.repo }}
# {{ required "chart.name is required for an application!" .chart.name }}
# {{ required "chart.version is required for an application!" .chart.version }}
# {{ required "overdrive.valuesFile is required for an application!" .overdrive.valuesFile }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    repoURL: {{ $.Values.repo.URL }}
    targetRevision: {{ $.Values.repo.targetRevision }}
    path: {{ $.Values.repo.path }}
    plugin:
      env:
        - name: HELM_REPO
          value: {{ .chart.repo }}
        - name: CHART_NAME
          value: {{ .chart.name }}
        - name: CHART_VERSION
          value: {{ .chart.version }}

        - name: BASE_VALUES
          value: {{ $.Values.overdriveConf.baseFolder }}/{{ .overdrive.valuesFile }}
        - name: BASE_GLOBAL
          value: {{ $.Values.overdriveConf.baseFolder }}/{{ $.Values.overdriveConf.globalsFile }}

        - name: ENV_VALUES
          value: {{ $.Values.overdriveConf.envFolder }}/{{ .overdrive.valuesFile }}
        - name: ENV_GLOBAL
          value: {{ $.Values.overdriveConf.envFolder }}/{{ $.Values.overdriveConf.globalsFile }}

{{- if .overdrive.additionalResources }}
        - name: BASE_ADDITIONAL_RESOURCES
          value: {{ $.Values.overdriveConf.baseFolder }}/{{ .overdrive.additionalResources }}
        - name: ENV_ADDITIONAL_RESOURCES
          value: {{ $.Values.overdriveConf.envFolder }}/{{ .overdrive.additionalResources }}
{{- end }}
  destination:
    server: {{ $.Values.destination }}
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}