apiVersion: v2
name: thanos
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
dependencies:
  - name: thanos
    version: "9.0.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: thanos.enabled
