apiVersion: v2
type: application
name: nidhogg
description: A chart that deploys nidhogg.
version: 2.0.0-rc.18
dependencies:
  - name: argo-cd
    version: 3.33.6
    repository: https://argoproj.github.io/argo-helm
  - name: cni
    version: 1.0.0
    repository: https://distributed-technologies.github.io/helm-charts
    condition: cni.enabled
  - name: lb-proxy
    version: 0.1.0
    repository: https://distributed-technologies.github.io/helm-charts
    condition: lb-proxy.enabled
