
# --- required parameters ---

repo:
  URL: # example: https://github.com/distributed-technologies/env-repo-template
  targetRevision: # example: main
  path: # example: .

overdriveConf:
  baseFolder: # example: /base
  envFolder: # example: /env/production 
  globalsFile: # example: globals.yaml

# --- additional parameters ---

destination: https://kubernetes.default.svc

nidhogg:
  # # if not configured, nidhogg wil not monitor itself
  # valuesFile: 
  chart:
    repo: https://martinschmidt.github.io/helm-charts/
    name: nidhogg
    version: 2.0.0-rc.12
  # additionalResources: 

yggdrasil:
  # # if not configured, yggdrasil will be disabled
  # valuesFile: 
  chart:
    repo: https://martinschmidt.github.io/helm-charts/
    name: yggdrasil
    version: 3.0.0-rc.5
  # additionalResources: 

cni:
  enabled: false

lb-proxy:
  enabled: false

additionalManifests:
  # # additional manifests can be added as a list.
  # - apiVersion: v1
  #   kind: Secret
  #   metadata:
  #     name: mysecret
  #   type: Opaque
  #   data:
  #     USER_NAME: YWRtaW4=
  #     PASSWORD: MWYyZDFlMmU2N2Rm

# --- default configurations ---

argo-cd:
  controller:
    replicas: 3
    env:
      - name: "ARGOCD_CONTROLLER_REPLICAS"
        value: "3"
    enableStatefulSet: true
  redis-ha:
    enabled: true
  redis:
    enabled: false
  repoServer:
    extraContainers:
      - name: helm-overdrive
        command: [/var/run/argocd/argocd-cmp-server]
        image: ghcr.io/distributed-technologies/argocd-plugin/helm-overdrive:0.0.0-pr.2-d56ef2d
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp-dir
  server:
    replicas: 3
    config:
      resource.customizations: |
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/0/namespaceSelector/matchExpressions/2
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
            