{{ $root := . }}
{{- range .Values.cephObjectStores -}}
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- with .annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec: {{ toYaml .spec | nindent 2 }}
{{- end }}
