{{ $root := . }}
{{- range .Values.objBucketClaims -}}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- with .annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec: {{ toYaml .spec | nindent 2 }}
{{- end -}}
