{{ $root := . }}
{{- range .Values.objBucketClaims }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
{{- with .spec }}
{{- toYaml . | nindent 2 }}
{{- end -}}

{{- end }}
