{{ $root := . }}
{{- range .Values.storageClass -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- with .annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
provisioner: {{ .provisioner }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- with .parameters }}
parameters:
{{ toYaml . | indent 2}}
{{- end }}
{{- end -}}
