---
{{- if (.Values.nidhogg).valuesFile }}
# {{ required ".Values.repo.URL is required!" .Values.repo.URL }}
# {{ required ".Values.repo.targetRevision is required!" .Values.repo.targetRevision }}
# {{ required ".Values.repo.path is required!" .Values.repo.path }}
# {{ required ".Values.overdriveConf.baseFolder is required!" .Values.overdriveConf.baseFolder }}
# {{ required ".Values.overdriveConf.envFolder is required!" .Values.overdriveConf.envFolder }}
# {{ required ".Values.overdriveConf.globalsFile is required!" .Values.overdriveConf.globalsFile }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nidhogg
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yggdrasil
  source:
    repoURL: {{ .Values.repo.URL }}
    targetRevision: {{ .Values.repo.targetRevision }}
    path: {{ .Values.repo.path }}
    plugin:
      env:
        - name: HELM_REPO
          value: {{ .Values.nidhogg.chart.repo }}
        - name: CHART_NAME
          value: {{ .Values.nidhogg.chart.name }}
        - name: CHART_VERSION
          value: {{ .Values.nidhogg.chart.version }}

        - name: BASE_VALUES
          value: {{ .Values.overdriveConf.baseFolder }}/{{ .Values.nidhogg.valuesFile }}
        - name: BASE_GLOBAL
          value: {{ .Values.overdriveConf.baseFolder }}/{{ .Values.overdriveConf.globalsFile }}

        - name: ENV_VALUES
          value: {{ .Values.overdriveConf.envFolder }}/{{ .Values.nidhogg.valuesFile }}
        - name: ENV_GLOBAL
          value: {{ .Values.overdriveConf.envFolder }}/{{ .Values.overdriveConf.globalsFile }}

{{- if .Values.nidhogg.additionalResources }}
        - name: BASE_ADDITIONAL_RESOURCES
          value: {{ .Values.overdriveConf.baseFolder }}/{{ .Values.nidhogg.additionalResources }}
        - name: ENV_ADDITIONAL_RESOURCES
          value: {{ .Values.overdriveConf.envFolder }}/{{ .Values.nidhogg.additionalResources }}
{{- end }}

  destination:
    server: {{ .Values.destination}}
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
