---
{{- if (.Values.yggdrasil).valuesFile }}
# {{ required ".Values.repo.repoURL is required!" .Values.repo.repoURL }}
# {{ required ".Values.repo.targetRevision is required!" .Values.repo.targetRevision }}
# {{ required ".Values.repo.path is required!" .Values.repo.path }}
# {{ required ".Values.baseFolder is required!" .Values.baseFolder }}
# {{ required ".Values.envFolder is required!" .Values.envFolder }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yggdrasil
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yggdrasil
  source:
    repoURL: {{ .Values.repo.repoURL }}
    targetRevision: {{ .Values.repo.targetRevision }}
    path: {{ .Values.repo.path }}
    plugin:
      name: helm-overdrive
      env:
        - name: HELM_REPO
          value: {{ .Values.yggdrasil.chart.repo }}
        - name: CHART_NAME
          value: {{ .Values.yggdrasil.chart.name }}
        - name: CHART_VERSION
          value: {{ .Values.yggdrasil.chart.version }}

        - name: BASE_VALUES
          value: {{ .Values.baseFolder }}/{{ .Values.yggdrasil.valuesFile }}
        - name: BASE_GLOBAL
          value: {{ .Values.baseFolder }}/{{ .Values.globalsFile }}

        - name: ENV_VALUES
          value: {{ .Values.envFolder }}/{{ .Values.yggdrasil.valuesFile }}
        - name: ENV_GLOBAL
          value: {{ .Values.envFolder }}/{{ .Values.globalsFile }}

{{- if .Values.yggdrasil.additionalResources }}
        - name: BASE_EXTRA
          value: {{ $.Values.baseFolder }}/{{ .Values.yggdrasil.additionalResources }}
        - name: ENV_EXTRA
          value: {{ $.Values.envFolder }}/{{ .Values.yggdrasil.additionalResources }}
{{- end }}
  destination:
    server: {{ .Values.destination}}
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}