{{ if .Values.dataexport.enable -}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker
metadata:
  name: dataexport
spec:
  replicas: 1
  consumer:
    bootstrapServers: {{ .Values.cluster.name }}-kafka-bootstrap:9092
    groupId: dataexport
    numStreams: 1
  producer:
    bootstrapServers: {{ .Values.dataexport.target.bootstrapserver }}
    abortOnSendFailure: true
  include: {{ .Values.dataexport.topics | join "," | quote }}
  resources:
    requests:
      cpu: "100m"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  logging:
    type: inline
    loggers:
      mirrormaker.root.logger: "INFO"
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  jvmOptions:
    "-Xmx": "1g"
    "-Xms": "1g"
{{- end }}
