on:
  push:
    branches:
      - feature/test-ceph

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      BLOCK: /dev/sdb
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: setup minikube
      run: |
        sudo modprobe nbd
        sudo apt update
        sudo apt install -y qemu-utils
        for i in {0..2}; do
          truncate -s 10G disk$i.img
          sudo qemu-nbd --connect=/dev/nbd$i --format=raw disk$i.img
        done
        kind create cluster --config ci/kind2.yaml
        for c in $(docker ps -q); do
          for d in $(); do
            docker exec $c rm $(lsblk -n -o PATH) || true
          done
        done
        kubectl delete storageclass standard
        kubectl create -f ci/pvc.yaml
        while true; do
          sleep 1
        done

    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

    - name: print k8s cluster status
      run: |
          kubectl cluster-info
          kubectl get pods -n kube-system

    - name: apply pod
      run: |
          until kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml; do sleep 1s; done

    - name: use local disk and create partitions for osds
      run: |
        .github/scripts/github-action-helper.sh use_local_disk
        .github/scripts/create-bluestore-partitions.sh --disk "$BLOCK" --osd-count 1
