on:
  push:
    branches:
      - feature/test-ceph

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      #uses: medyagh/setup-minikube@master
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: 'v1.24.0'
        kubernetes version: 'v1.20.9'
        github token: ${{ secrets.GITHUB_TOKEN }}

#    - name: install pod
#      run: kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
    
    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Try the cluster !11
      run: kubectl get sa
