on:
  push:
    branches:
      - feature/test-ceph

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      #uses: medyagh/setup-minikube@master
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.21.0'
        github token: ${{ secrets.GITHUB_TOKEN }}
    - name: Try the cluster !
      run: kubectl get pods -A
