on:
  push:
    branches:
      - feature/test-ceph

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      BLOCK: /dev/sdb
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: setup minikube
      run: |
        sudo swapoff /mnt/swapfile
        sudo umount /mnt
        sudo blkdiscard /dev/sda
        sudo fdisk -l
        sudo swapon
        mount
        df -h
        exit 1
        minikube start --memory 6g --cpus=2 --driver=docker
        

    - name: print k8s cluster status
      run: |
          kubectl cluster-info
          kubectl get pods -n kube-system

    - name: apply pod
      run: |
          until kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml; do sleep 1s; done

    - name: use local disk and create partitions for osds
      run: |
        .github/scripts/github-action-helper.sh use_local_disk
        .github/scripts/create-bluestore-partitions.sh --disk "$BLOCK" --osd-count 1
